// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDkg23yoTr-E7aD2YSUWUZRh-ZPq4W-g',
    appId: '1:183949458364:web:b5401b6dc38b41c4f489b9',
    messagingSenderId: '183949458364',
    projectId: 'axiom-serviceprovider',
    authDomain: 'axiom-serviceprovider.firebaseapp.com',
    storageBucket: 'axiom-serviceprovider.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLfZPM93AG-qp5rNxVQ84ZA7Xx_ZZYMg',
    appId: '1:183949458364:android:cdb27f5358cde871f489b9',
    messagingSenderId: '183949458364',
    projectId: 'axiom-serviceprovider',
    storageBucket: 'axiom-serviceprovider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtNr_EvPpJMR82tBzh0LxR6I1dEznx_Ic',
    appId: '1:183949458364:ios:826451254718dde3f489b9',
    messagingSenderId: '183949458364',
    projectId: 'axiom-serviceprovider',
    storageBucket: 'axiom-serviceprovider.firebasestorage.app',
    androidClientId: '183949458364-cfotvb72v4t1bjb7vks4o4qlbevvdvkk.apps.googleusercontent.com',
    iosClientId: '183949458364-i1qqb9nq3muk85qlsqfcbgg8mougg87g.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtNr_EvPpJMR82tBzh0LxR6I1dEznx_Ic',
    appId: '1:183949458364:ios:826451254718dde3f489b9',
    messagingSenderId: '183949458364',
    projectId: 'axiom-serviceprovider',
    storageBucket: 'axiom-serviceprovider.firebasestorage.app',
    androidClientId: '183949458364-cfotvb72v4t1bjb7vks4o4qlbevvdvkk.apps.googleusercontent.com',
    iosClientId: '183949458364-i1qqb9nq3muk85qlsqfcbgg8mougg87g.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNDkg23yoTr-E7aD2YSUWUZRh-ZPq4W-g',
    appId: '1:183949458364:web:0653028589c30274f489b9',
    messagingSenderId: '183949458364',
    projectId: 'axiom-serviceprovider',
    authDomain: 'axiom-serviceprovider.firebaseapp.com',
    storageBucket: 'axiom-serviceprovider.firebasestorage.app',
  );
}
